# My first Github actions work--------------

name: CI-CD-to-AWS
env:
 EB_PACKAGE_S3_BUCKET_NAME : "github.aad1486"
 EB_APPLICATION_NAME       : "Githubtest"
 EB_ENVIRONMENT_NAME       : "Githubtest-env"
 DEPLOY_PACKAGE_NAME       : "flask_app_$ {{ github.sha }}.zip"
 AWS_REGION_NAME           : "eu-north-1" 
 
 


on: 
  push:
    branches: [ main ]

jobs: 
  CI_part:
    runs-on: ubuntu-latest


    steps:
      - name: Git clone our repo
      - uses: actions/checkout@v3
      
      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x * -git*
        
